<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { request, errorText } from '../api'
import { useAuth } from '../stores/auth'
const props=defineProps<{productId:string}>()
type Review={id:string;author:string;rating:number;content:string;reply:string;createdAt:string;mine:boolean;purchased:boolean}
const reviews=ref<Review[]>([]),rating=ref(5),content=ref(''),busy=ref(false),error=ref(''),notice=ref(''),auth=useAuth()
const hoveredRating=ref(0)
async function load(){try{reviews.value=await request('GET',`/products/${props.productId}/reviews`)}catch(e){error.value=errorText(e)}}
async function submit(){if(busy.value)return;if(!auth.authenticated&&!await auth.requestLogin())return;busy.value=true;error.value='';notice.value='';try{await request('POST',`/products/${props.productId}/reviews`,undefined,{rating:rating.value,content:content.value});content.value='';await load();notice.value='评论已发布。每款衣服保留你最新的一条评论。'}catch(e){error.value=errorText(e)}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="section reviews"><h2>衣友留言</h2><p class="caption">分享款式、穿搭和体验。</p><p v-if="error" class="error" role="alert">{{ error }} <button @click="load">重试</button></p><article v-for="r in reviews" :key="r.id" class="review"><div class="between"><strong>{{ r.author }} <span class="stars">{{ '★'.repeat(r.rating) }}{{ '☆'.repeat(5-r.rating) }}</span></strong><small>{{ new Date(r.createdAt).toLocaleDateString('zh-CN') }}</small></div><p v-if="r.purchased" class="caption">已完成模拟订单</p><p>{{ r.content }}</p><p v-if="r.reply" class="merchant-reply">掌柜回复：{{ r.reply }}</p></article><p v-if="!reviews.length" class="state">还没有公开留言，欢迎写下第一条。</p><form class="panel" @submit.prevent="submit"><fieldset class="rating-field" :disabled="busy"><legend>评分</legend><div class="rating-stars" @mouseleave="hoveredRating=0"><label v-for="n in 5" :key="n" class="rating-star" @mouseenter="hoveredRating=n"><input v-model.number="rating" type="radio" :name="'review-rating-'+productId" :value="n" :aria-label="n+'星'" @focus="hoveredRating=0"><span aria-hidden="true" :class="{filled:n<=(hoveredRating||rating)}">{{ n<=(hoveredRating||rating)?'★':'☆' }}</span></label></div></fieldset><label>你的评论<textarea v-model="content" minlength="5" maxlength="2000" rows="3" required placeholder="写下5至2000字的体验或建议"/></label><button class="primary" :disabled="busy">{{ busy?'提交中…':auth.authenticated?'提交评论':'登录并提交评论' }}</button><p v-if="notice" class="notice" role="status">{{ notice }}</p></form></section></template>
<style scoped>.review{padding:24px 0;border-top:1px solid var(--line)}.stars{color:var(--wood);font-size:14px;margin-left:12px}.merchant-reply{padding:14px;background:#ece8dd;border-radius:8px;font-size:13px}.rating-field{border:0;padding:0;margin:0 0 18px;min-width:0}.rating-field legend{padding:0;margin-bottom:5px}.rating-stars{display:inline-flex;align-items:center;gap:2px}.rating-star{position:relative;display:inline-flex;align-items:center;justify-content:center;width:28px;height:38px;margin:0;cursor:pointer}.rating-star input{position:absolute;inset:0;width:100%;height:100%;margin:0;opacity:0;cursor:pointer;z-index:1}.rating-star span{font-size:25px;line-height:1;color:#b8a58e;transition:color .15s}.rating-star span.filled{color:var(--wood)}.rating-star input:focus-visible+span{outline:2px solid var(--wood);outline-offset:3px;border-radius:3px}.rating-field:disabled{opacity:.6}.rating-field:disabled .rating-star,.rating-field:disabled input{cursor:default}</style>
