<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { request,errorText } from '../api'
import { money } from '../types'
import type { RetailRun,RetailMetrics } from '../retail'
import { retailStates,sourceLinks } from '../retail'
import { useSession } from '../stores/session'
const props=defineProps<{admin?:boolean}>()
const runs=ref<RetailRun[]>([]),metrics=ref<RetailMetrics>(),filter=ref('ALL'),origin=ref('LIVE'),busy=ref(false),error=ref(''),notice=ref(''),replies=ref<Record<string,string>>({}),choices=ref<Record<string,string>>({}),confirmation=ref<{run:RetailRun;sku:string}>()
const store=useSession()
const shown=computed(()=>runs.value.filter(r=>(!props.admin||r.origin===origin.value)&&(filter.value==='ALL'||(filter.value==='OPEN'?r.cases.some(c=>c.state==='OPEN'):r.status===filter.value))))
async function load(){error.value='';try{const root=props.admin?'/admin/retail':'/retail';runs.value=await request('GET',root+'/runs');if(props.admin)metrics.value=await request('GET',root+'/metrics')}catch(e){error.value=errorText(e)}}
async function run(action:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await action();await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
const help=(id:string)=>run(async()=>{await request('POST','/retail/runs/'+id+'/help',undefined,{});notice.value='已提交商家待办，可在此查看回复。'})
const resolve=(id:string)=>run(async()=>{await request('PUT','/admin/retail/cases/'+id,undefined,{reply:replies.value[id]});notice.value='回复已发送，待办已完成。'})
const confirm=()=>run(async()=>{if(!confirmation.value)return;await request('POST','/retail/runs/'+confirmation.value.run.id+'/confirm',undefined,{skuId:confirmation.value.sku});confirmation.value=undefined;store.confirmCartAddition();notice.value='已确认加入衣囊。'})
function exportRows(){const data={exportedAt:new Date().toISOString(),scope:'最近200条脱敏接待，非全部原始数据；全库统计单独提供',metrics:metrics.value,runs:runs.value};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='retail-reception.json';a.click();URL.revokeObjectURL(url)}
onMounted(load)
</script>
<template>
  <section class="retail-history">
    <div class="between"><div><h2>{{ admin?'AI 接待与待办':'我的选购记录' }}</h2><p class="caption">{{ admin?'查看真实接待、规格核对及需要人工处理的问题。最近 200 条记录。':'最近 50 次接待；刷新或重新登录后仍可查看选购与商家回复。' }}</p></div><div class="actions"><button :disabled="busy" @click="load">刷新记录</button><button v-if="admin" :disabled="!runs.length" @click="exportRows">导出脱敏记录</button></div></div>
    <div v-if="metrics" class="retail-metrics"><article><span>接待次数</span><strong>{{ metrics.total }}</strong></article><article><span>确认加购</span><strong>{{ metrics.confirmed }}</strong></article><article><span>待处理 / 已处理</span><strong>{{ metrics.openCases }} / {{ metrics.resolvedCases }}</strong></article><article><span>失败次数</span><strong>{{ metrics.failed }}</strong></article><article><span>P95 用时</span><strong>{{ metrics.p95Ms===null?'—':(metrics.p95Ms/1000).toFixed(1)+'秒' }}</strong></article></div>
    <p v-if="metrics" class="caption">{{ metrics.scope }}。{{ metrics.costNote }}</p>
    <div class="actions"><label v-if="admin" class="retail-filter">来源<select v-model="origin"><option value="LIVE">用户接待</option><option value="EVALUATION">独立评测（不计入接待）</option></select></label><label class="retail-filter">筛选<select v-model="filter"><option value="ALL">全部记录</option><option value="OPEN">商家待处理</option><option value="CONFIRMED">已确认加购</option><option value="FAILED">处理失败</option><option value="NO_MATCH">暂无匹配</option></select></label></div>
    <p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="notice" class="notice" role="status">{{ notice }}</p>
    <p v-if="!shown.length" class="state">暂无匹配的接待记录。完成一次问衣后会保存真实记录。</p>
    <article v-for="r in shown" :key="r.id" class="panel reception">
      <div class="between"><strong>{{ r.dynasty? r.dynasty+'代衣裳选购':'衣裳选购' }}</strong><span class="tag">{{ retailStates[r.status]||r.status }}</span></div><small>{{ new Date(r.created_at).toLocaleString('zh-CN') }} · {{ r.id.slice(0,8) }}</small>
      <p>{{ r.summary }}</p><div class="chips"><span class="tag">预算 {{ r.budget===null?'不限':money(r.budget) }}</span><span class="tag">{{ r.size_label||'尺码未限定' }}</span><span class="tag">{{ r.color_label||'颜色未限定' }}</span><span class="tag">{{ r.quantity }} 件</span></div>
      <details v-if="r.candidates.length"><summary>当时核验的候选规格 · {{ r.candidates.length }} 项</summary><ul><li v-for="c in r.candidates" :key="c.sku_id">{{ c.name }} · {{ c.color }} / {{ c.size_label }} · {{ money(c.quoted_price) }} <span v-if="c.deleted_at||c.status!=='ACTIVE'">（当前已下架）</span></li></ul><p class="caption">以上价格为接待时记录，确认时会重新查询当前价格与库存。</p></details>
      <div v-if="!admin&&['DONE','HANDOFF'].includes(r.status)&&r.candidates.length" class="actions"><select v-model="choices[r.id]" aria-label="选择记录中的规格"><option :value="undefined" disabled>请选择规格</option><option v-for="c in r.candidates" :key="c.sku_id" :value="c.sku_id" :disabled="!!c.deleted_at||c.status!=='ACTIVE'">{{ c.name }} · {{ c.color }}/{{ c.size_label }} · {{ money(c.quoted_price*r.quantity) }}</option></select><button class="primary" :disabled="busy||!choices[r.id]" @click="confirmation={run:r,sku:choices[r.id]!}">确认选购</button></div>
      <RouterLink v-if="!admin&&r.selections.length" to="/cart">查看衣囊 →</RouterLink>
      <div v-for="c in r.cases" :key="c.created_at" class="case"><strong>{{ c.state==='OPEN'?'商家待处理':'商家已处理' }}</strong><p>{{ c.reason }}</p><p v-if="c.reply" class="merchant-reply">商家回复：{{ c.reply }}</p><template v-if="admin&&c.state==='OPEN'"><label>处理回复<textarea v-model="replies[r.id]" rows="3" maxlength="2000" placeholder="说明核对结果或可行的替代方案"/></label><button class="primary" :disabled="busy||!replies[r.id]?.trim()" @click="resolve(r.id)">回复并完成待办</button></template></div>
      <button v-if="!admin&&!r.cases.length&&r.status!=='RUNNING'" :disabled="busy" @click="help(r.id)">请商家协助</button>
      <details v-if="admin" class="execution"><summary>执行证据与来源</summary><p>{{ r.model_calls }} 次模型调用 · {{ r.tool_calls }} 次模型工具请求 · {{ r.elapsed_ms===null?'尚未结束':(r.elapsed_ms/1000).toFixed(1)+'秒' }}</p><p>输入 / 输出 Token：{{ r.input_tokens??'未返回' }} / {{ r.output_tokens??'未返回' }}</p><ol><li v-for="step in r.steps" :key="step.step_number"><b>{{ step.kind==='SERVER_TOOL'?'服务端预查询':step.kind==='MODEL_TOOL'?'模型调用工具':step.kind==='MODEL'?'真实模型响应':'服务端约束核对' }}</b> · {{ step.detail }} · {{ step.elapsed_ms }}ms</li></ol><article v-for="(e,i) in r.evidence" :key="i"><strong>{{ e.title_at_query }}</strong><p>{{ e.excerpt_at_query }}</p><a v-for="url in sourceLinks(e.source_at_query)" :key="url" :href="url" target="_blank" rel="noopener noreferrer">查看来源 ↗</a></article></details>
    </article>
    <div v-if="confirmation" class="selection-overlay"><section role="dialog" aria-modal="true" aria-labelledby="history-confirm-title" class="panel"><h2 id="history-confirm-title">确认本次选购</h2><p>{{ confirmation.run.candidates.find(c=>c.sku_id===confirmation?.sku)?.name }} · {{ confirmation.run.candidates.find(c=>c.sku_id===confirmation?.sku)?.color }} / {{ confirmation.run.candidates.find(c=>c.sku_id===confirmation?.sku)?.size_label }} × {{ confirmation.run.quantity }}</p><p>合计 {{ money(Number(confirmation.run.candidates.find(c=>c.sku_id===confirmation?.sku)?.quoted_price)*confirmation.run.quantity) }}</p><p>确认后加入衣囊，不会扣款。</p><p v-if="error" class="error">{{ error }}</p><div class="actions"><button :disabled="busy" @click="confirmation=undefined">取消</button><button class="primary" :disabled="busy" @click="confirm">确认加入衣囊</button></div></section></div>
  </section>
</template>
<style scoped>
.retail-history>.between{gap:20px;flex-wrap:wrap}.retail-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:20px 0}.retail-metrics article{padding:20px;background:var(--silk);border:1px solid var(--line);border-radius:12px}.retail-metrics span{font-size:12px;color:var(--muted)}.retail-metrics strong{display:block;font-size:26px;margin-top:12px}.retail-filter{display:flex;gap:12px;align-items:center;margin:16px 0}.retail-filter select{width:180px}.reception{margin:16px 0}.reception>small{display:block;color:var(--muted);margin-top:8px}.reception details{margin:16px 0;font-size:13px}.reception details li{line-height:2}.reception>.actions{margin-top:15px;flex-wrap:wrap}.reception select{max-width:100%}.case{background:#f0ece2;border-left:3px solid var(--wood);padding:18px;margin:18px 0}.case textarea{display:block;width:100%;margin:8px 0}.execution article{border-top:1px solid var(--line);padding:15px 0}.selection-overlay{position:fixed;inset:0;background:#0007;z-index:120;display:grid;place-items:center;padding:20px}.selection-overlay>section{max-width:520px;width:100%;background:var(--silk)}@media(max-width:760px){.retail-metrics{grid-template-columns:repeat(2,1fr)}}
</style>
