<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { request } from '../api'
import { useAsync } from '../composables/useAsync'
import { useSession } from '../stores/session'
import { useAuth } from '../stores/auth'
import type { Product, KnowledgeResult, Cart } from '../types'
import { money } from '../types'
import ProductArt from '../components/ProductArt.vue'
import KnowledgePanel from '../components/KnowledgePanel.vue'
import EmptyErrorLoading from '../components/EmptyErrorLoading.vue'
import ProductReviews from '../components/ProductReviews.vue'
const store = useSession(), session = store.current, route = useRoute(), product = ref<Product>(), color = ref(''), skuId = ref(''), dialog = ref<HTMLDialogElement>(), knowledge = ref<KnowledgeResult>()
const init = useAsync(), extra = useAsync(), action = useAsync(), auth = useAuth()
const sku = computed(() => product.value?.skus.find(s => s.id === skuId.value))
function chooseColor(value: string) { color.value = value; skuId.value = product.value?.skus.find(s => s.color === value && s.stock > 0)?.id || '' }
function applyRequestedSku() { const requested = product.value?.skus.find(item => item.id === route.query.skuId && item.stock > 0); if (requested) { color.value = requested.color; skuId.value = requested.id } }
const loadExtra = () => extra.run(async () => { if(!product.value) return; knowledge.value = await request<KnowledgeResult>('GET',`/products/${product.value.id}/references`,session.id) })
const load = () => init.run(async () => { product.value = await request<Product>('GET',`/products/${encodeURIComponent(String(route.params.id))}`,session.id); chooseColor(product.value.colors[0] || ''); applyRequestedSku(); void loadExtra() })
const add = () => action.run(async () => { if(!product.value || !sku.value) return; const productId = product.value.id, selectedSkuId = sku.value.id; if (!auth.authenticated && !await auth.requestLogin('', '登录后将继续把这件衣服加入你的衣囊。')) return; const activeSessionId = store.current.id; const cart = await request<Cart>('GET','/cart',activeSessionId); await request('POST','/cart',activeSessionId,{productId,skuId:selectedSkuId,quantity:(cart.lines.find(l => l.skuId === selectedSkuId)?.quantity || 0) + 1}); store.confirmCartAddition() })
onMounted(load)
</script>
<template><div class="page narrow"><RouterLink to="/">宫门</RouterLink><span class="muted"> / 衣裳详情</span><EmptyErrorLoading :loading="init.loading.value" :error="init.error.value" @retry="load"><template v-if="product"><div class="product-detail"><ProductArt :product="product"/><section class="product-information"><p class="eyebrow">{{ product.dynasty }} · {{ product.form }}</p><h1>{{ product.name }}</h1><p>{{ product.description }}</p><div class="chips"><span v-for="tag in product.tags" :key="tag" class="tag">{{ tag }}</span></div><p class="price">{{ sku ? money(sku.price) : '请选择可售规格' }}</p><fieldset><legend>颜色</legend><div class="chips"><button v-for="value in product.colors" :key="value" :aria-pressed="color === value" :class="{selected:color === value}" @click="chooseColor(value)">{{ value }}</button></div></fieldset><fieldset><legend>尺码</legend><div class="chips"><button v-for="s in product.skus.filter(s => s.color === color)" :key="s.id" :disabled="s.stock < 1" :aria-pressed="skuId === s.id" :class="{selected:skuId === s.id}" @click="skuId = s.id">{{ s.size }}{{ s.stock ? '' : ' · 缺货' }}</button></div></fieldset><p v-if="sku">库存 {{ sku.stock }} 件 · 服务端下单时再次校验</p><div class="actions"><button @click="dialog?.showModal()">查看尺码表</button><RouterLink class="button" :to="{path:'/guide',query:{mode:'size',productId:product.id,skuId:sku?.id}}">问尺码助手</RouterLink><RouterLink class="button" :to="{path:'/support',query:{productId:product.id}}">咨询客服</RouterLink></div><div class="actions"><RouterLink v-if="sku" class="button primary" :to="{path:'/tryon',query:{productId:product.id,skuId:sku.id}}">看我穿上 ↗</RouterLink><button :disabled="!sku || action.loading.value" @click="add">加入衣囊</button></div><p v-if="action.error.value" class="error" role="alert">{{ action.error.value }}<button @click="add">重试</button></p><p class="caption">商品图片为 AI 设计示意，非商品实拍、非文物复原；尺码建议不保证合身。</p></section></div><section class="section"><h2>衣冠有来处</h2><EmptyErrorLoading :loading="extra.loading.value" :error="extra.error.value" @retry="loadExtra"><KnowledgePanel v-if="knowledge" :knowledge="knowledge"/></EmptyErrorLoading></section><ProductReviews :key="product.id" :product-id="product.id"/><dialog ref="dialog" aria-labelledby="size-heading"><div class="between"><h2 id="size-heading">{{ product.name }} · 尺码表</h2><button autofocus @click="dialog?.close()" aria-label="关闭尺码表">×</button></div><p>单位：厘米。区间由后端商品目录提供。</p><div class="table-scroll"><table><thead><tr><th>尺码</th><th>身高</th><th>胸围</th><th>腰围</th><th>臀围</th></tr></thead><tbody><tr v-for="row in product.sizeChart" :key="row.size"><td>{{ row.size }}</td><td v-for="key in (['height','chest','waist','hip'] as const)" :key="key">{{ row[key].min }}–{{ row[key].max }}</td></tr></tbody></table></div><p v-if="!product.sizeChart.length">暂无尺码表。</p><p>缺少围度时不从体重推断，请咨询后再选码。</p><button @click="dialog?.close()">了解了</button></dialog></template></EmptyErrorLoading></div></template>
