<script setup lang="ts">
import { reactive, ref, onBeforeUnmount } from 'vue'
import { request } from '../api'
import { useSession } from '../stores/session'
import { useAuth } from '../stores/auth'
import { useAsync } from '../composables/useAsync'
import type { Body } from '../types'
const store = useSession(), auth = useAuth(), session = store.current, action = useAsync(), message = ref('')
const fields = [{key:'height',label:'身高（厘米）',min:80,max:230},{key:'weightKg',label:'体重（公斤）',min:20,max:250},{key:'chest',label:'胸围（厘米）',min:40,max:180},{key:'waist',label:'腰围（厘米）',min:35,max:180},{key:'hip',label:'臀围（厘米）',min:40,max:200}] as const
const values = reactive({height:'',weightKg:'',chest:'',waist:'',hip:'',loose:false})
function clear() { fields.forEach(f => { values[f.key] = '' }); values.loose = false }
const save = () => action.run(async () => { const body: Body = {height:null,weightKg:null,chest:null,waist:null,hip:null,loose:values.loose}; fields.forEach(f => { body[f.key] = values[f.key] === '' ? null : Number(values[f.key]) }); await request('PUT','/user/body-profile',session.id,body); clear(); message.value = '身材资料已保存到当前后端会话。表单已清空，不回显原始数值。' })
const removeBody = () => action.run(async () => { await request('DELETE','/user/body-profile',session.id); clear(); message.value = '当前会话身材资料已删除。' })
const inspect = () => action.run(async () => { const body = await request<Body | null>('GET','/user/body-profile',session.id); message.value = body && fields.some(f => body[f.key] !== null) ? '当前会话已保存部分身材资料；出于隐私保护不显示数值。' : '当前会话未保存身材数值。' })
const removePortrait = (id: string) => action.run(async () => { await request('DELETE',`/tryon/portrait/${id}`,session.id); session.portraits = session.portraits.filter(p => p.id !== id); session.tasks = session.tasks.filter(t => !t.originalUrl?.includes('/portrait/' + encodeURIComponent(id) + '/image')); message.value = '本站保存的人像及其关联结果已删除。火山引擎的处理与保留规则以其服务条款及隐私政策为准。' })
const cancelTask = (id: string) => action.run(async () => { await request('POST',`/tryon/tasks/${id}/cancel`,session.id); session.tasks = session.tasks.filter(t => t.id !== id); message.value = '本次任务结果已从本站删除。若请求已经发送，图像服务仍可能继续处理或计费。' })
onBeforeUnmount(clear)
</script>
<template><div class="page narrow"><div class="page-heading"><p class="eyebrow">我的 · 个人中心</p><h1>{{ auth.user?.displayName || auth.user?.username }}，长安相逢</h1><p>账号：{{ auth.user?.username }}。不把身材、人像、聊天输入写入浏览器持久化存储。</p><div class="actions"><RouterLink class="button primary" to="/orders">查看购物订单</RouterLink><RouterLink class="button" to="/cart">我的衣囊</RouterLink></div></div><div class="two-column"><section class="panel"><h2>身材小笺</h2><p>仅用于当前会话的区间尺码建议。可只填写已知数据，不会从体重推算围度。保存会覆盖原资料，留空字段也会清空。</p><form @submit.prevent="save"><div class="form-grid"><label v-for="f in fields" :key="f.key" :for="f.key">{{ f.label }}<input :id="f.key" v-model="values[f.key]" type="number" :min="f.min" :max="f.max" step="0.1" autocomplete="off"></label></div><label class="check"><input v-model="values.loose" type="checkbox">偏好宽松</label><div class="actions"><button class="primary" :disabled="action.loading.value">保存资料</button><button type="button" :disabled="action.loading.value" @click="removeBody">删除身材资料</button><button type="button" :disabled="action.loading.value" @click="inspect">查询是否已保存</button></div></form></section><section class="panel"><h2>人像授权与删除</h2><p>人像会转换为 PNG 并临时保存在本站内存中，人像及关联试穿结果最长保留 30 分钟。生成时，人像和服饰图片将发送至火山引擎，通过「图片换装 V2」生成试穿效果。删除可清除本站保存的人像及关联结果，不代表火山引擎的服务副本也已删除；其处理与保留规则以其服务条款及隐私政策为准。</p><div v-for="(p,index) in session.portraits" :key="p.id" class="portrait-row"><h3>已授权人像 {{ index + 1 }}</h3><p>到期：{{ new Date(p.expiresAt).toLocaleString('zh-CN') }}</p><button :disabled="action.loading.value" @click="removePortrait(p.id)">删除人像及关联结果</button></div><p v-if="!session.portraits.length" class="state">本会话暂无已上传人像。</p><RouterLink class="button" to="/tryon">前往试衣镜</RouterLink><h3>本会话任务</h3><div v-for="task in session.tasks" :key="task.id" class="portrait-row"><RouterLink :to="{path:'/result/' + task.id,query:{sessionId:session.id}}">查看试穿任务</RouterLink><button :disabled="action.loading.value" @click="cancelTask(task.id)">取消任务 / 删除结果</button></div><p v-if="!session.tasks.length" class="muted">暂无任务。</p></section></div><p v-if="message" class="notice" role="status">{{ message }}</p><p v-if="action.error.value" class="error" role="alert">{{ action.error.value }}，请核对后重新操作。已过期资源由服务端清理。</p><section class="panel section"><h2>会话与隐私边界</h2><p>当前：{{ session.name }}。问衣、身材资料和试穿任务归属于当前登录账号的本次会话；购物订单归入当前账号，可在重新登录后查询。</p><p>退出登录或刷新页面会清空本页的会话、人像与试穿索引；这不等同于第三方服务删除图像。本站人像及关联结果最长保留 30 分钟，离开前也可在此主动删除。请勿在公共设备上保持登录。</p><RouterLink class="button" to="/guide">切换 / 新建问衣会话</RouterLink></section></div></template>


